### ISSUE TITLE
[Docs]도커 이미지 사용법

### ISSUE THREAD

**Issue by always0ne** [me-X-us/convert-motion-mask#10]
## for GPU
```
sudo docker run -itd --gpus all --name segmentation docker.pkg.github.com/me-x-us/convert-motion-mask/shape-estimation-gpu:9b2f00b05196605059faf9b6813109ca66f900fe
```
실행

**Comment by yeoV** [comment]
이 이미지 쓰려면 docker desktop 지우고 쉘에서 설치해야 하는거야???

**Comment by always0ne** [comment]
그런식으로 해야하는데 확인부탁하는건 GPU없는 환경에선 어떻게 되는지야
지금은 gpu버전, nongpu버전 둘다 되게 되어있어

**Comment by yeoV** [comment]
저거 해당 옵션으로 이미지 run 시키면 --gpus 때문에 GPU가 없는 환경에서, 이미지가 아예 안받아진당
![image](https://user-images.githubusercontent.com/59818703/99872114-de98d400-2c22-11eb-98e0-8be715a5d545.png)

**Comment by always0ne** [comment]
확인. 그러면 GPU, NonGPU 둘다 빌드하는걸로
