### ISSUE TITLE
[feat] shape estimation 리턴 값에 대해서

### ISSUE THREAD

**Issue by yeoV** [me-X-us/convert-motion-mask#12]
기능 :  shape estimation 메소드를 flask에서 호출 후 리턴 값 받기

1) 비디오의 전체 프레임 수
2) 비디오의 전체 길이 (단위 : msec)
사용자 webcam의 포즈 비교를 위해서 해당 정보가 필요 할 것 같음..!

*토의사항
1) 해당 리턴 값들은 어떤 형식으로 반환해 주어야 하는지!? (str, str)
2) 만약 1msec 당 프레임 수 어차피 계산해야 하면, 프론트에서 하지 말고 그냥 애초에 1msec당 frame수 반환하는건??
@naemoo

**Comment by yeoV** [comment]
생각해봤는데 그냥 비디오의 fps 값을 반환시키면, 동영상 특정 시점의 frame 번호를 알 수 있지 않을까??
에를 들면, 25fps 비디오라면 1분 30초 일때, 90초니까 90 * 25 하면 몇번째 frame 인지 알 수 있지않나?!

**Comment by naemoo** [comment]
90.00초면 90 * 25 맞는데 90.xx 초에는 몇번째 frame인지 msec로 계산해야함

**Comment by yeoV** [comment]
근데 우리가 저장된 좌표값이 int단위로 저장되어 있는데, 324.5 frame 이런식으로 나오면 버림해서 324 프레임부터 시작해야 되는거임??
